### ISSUE TITLE
If Response-XXX Specified, Remove Default Responses Key

### ISSUE THREAD

**Issue by homestar9** [coldbox-modules/swagger-sdk#14]
The Swagger specs require that paths have at least one response, which is why Util.cfc includes some defaults:
https://github.com/coldbox-modules/swagger-sdk/blob/719cb07d57fde8980c0f77556593c8edbfb2e536/models/OpenAPI/Util.cfc#L57-L69

However, if a handler specifies one or more @response-xxx annotations, then the default should be removed. Otherwise there will always be an extra empty `responses.default` key.

Why is this important?  Many UI tools like cbswaggerUI, Redoc, and more look at the response code (200, 400, etc) and will change the color based on their value:
![image](https://user-images.githubusercontent.com/5341142/200086938-95d9ab7a-be7b-4122-8be7-b4de1403ba42.png)

Adding an additional `default` response adds another empty response that never gets used.

![image](https://user-images.githubusercontent.com/5341142/200087285-9c47fa24-9a0b-4842-bb7d-44e85c61b8df.png)

Perhaps if there was a way to detect if no responses were specified and then include the defaults?

**Comment by jclausen** [comment]
I'm going to look in to this today and add some tests.  Ultimately, the removal of this default might be more the responsibility of the `cbSwagger` module, rather than the SDK.

**Comment by jclausen** [comment]
Duplicates https://github.com/coldbox-modules/cbSwagger/issues/28
