### ISSUE TITLE
Internal References Not Working

### ISSUE THREAD

**Issue by homestar9** [coldbox-modules/swagger-sdk#16]
If you want to reference an internal schema in a swagger file, you use a notation like `"$ref": "#/components/schemas/User" }`, however I don't think the parser handles these statements properly here:
https://github.com/coldbox-modules/swagger-sdk/blob/719cb07d57fde8980c0f77556593c8edbfb2e536/models/OpenAPI/Parser.cfc#L219

If I'm reading this right, the parser should simply return the $ref in a struct instead of executing the `getInternalXPath()` method. 
```
return { "$ref" : $ref };
```

Including (aka "zooming into") the reference isn't always effective because some swagger keys are allowed in the `schemas` definitions (like `allOf`) but are not allowed in response `schema`. Therefore it's better to refer to them instead.

**Comment by homestar9** [comment]
https://github.com/coldbox-modules/swagger-sdk/pull/17

**Comment by jclausen** [comment]
This is resolved in v3 of `swagger-sdk` ( commit #35e1a7d - currently in pre-release snapshot ).
